In [9]:
from transformers import DecisionTransformerModel, DecisionTransformerConfig
import numpy as np
import torch

device = "cpu"

scale = 1000.0  # normalization for rewards/returns
TARGET_RETURN = 3600 / scale  # evaluation conditioning targets, 3600 is reasonable from the paper LINK
state_dim = (3, 32, 32)
act_dim = 6

In [49]:
state_dim_flatten = state_dim[0]*state_dim[1]*state_dim[2]

t = 3
target_return = torch.tensor(TARGET_RETURN, device=device, dtype=torch.float32).reshape(1, 1)
states = torch.rand(state_dim, device=device, dtype=torch.float32).reshape(1, 1, state_dim_flatten)
actions = torch.rand((1, act_dim), device=device, dtype=torch.float32)
rewards = torch.rand((1, 1), device=device, dtype=torch.float32)
timesteps = torch.tensor(0, device=device, dtype=torch.long).reshape(1, 1)
attention_mask = torch.zeros(1, 1, device=device, dtype=torch.float32)


print(states.shape)
print(actions.shape)
print(rewards.shape)
print(target_return.shape)

config = DecisionTransformerConfig(state_dim_flatten, act_dim, max_ep_len=4096)


model = DecisionTransformerModel(config).to(device)
model.eval()

state_preds, action_preds, return_preds = model(states=states,
        actions=actions,
        rewards=rewards,
        returns_to_go=target_return,
        timesteps=timesteps,
        attention_mask=attention_mask,
        return_dict=False)

state_preds, action_preds, return_preds

torch.Size([1, 1, 3072])
torch.Size([1, 6])
torch.Size([1, 1])
torch.Size([1, 1])


(tensor([[[-0.1079,  0.5440, -0.2023,  ...,  0.1443, -0.1405,  0.1818]]],
        grad_fn=<ViewBackward0>),
 tensor([[[-0.0326, -0.0673, -0.2764, -0.0077,  0.1668, -0.2994]]],
        grad_fn=<TanhBackward0>),
 tensor([[[-0.1395]]], grad_fn=<ViewBackward0>))